name: zerocracy
'on':
  schedule:
    - cron: '1 * * * *'
concurrency:
  group: zerocracy
  cancel-in-progress: false
jobs:
  zerocracy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: zerocracy/judges-action@0.11.0
        with:
          token: ${{ secrets.ZEROCRACY_TOKEN }}
          github-token: ${{ secrets.ZEROCRACY_PAT }}
          repositories:  timofey-neyenburg/microframework
          factbase: microframework.fb
      - uses: zerocracy/pages-action@0.1.5
        with:
          github-token: ${{ secrets.ZEROCRACY_PAT }}
          factbase: microframework.fb
      - uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: pages
          clean: false
